apiVersion: v1
kind: Service
metadata:
  name: spp-monolith
  labels:
    app: spp-monolith
spec:
  selector:
    app: spp-monolith
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: ClusterIP
